<a href="https://colab.research.google.com/github/007arjungangwar/Foundations-of-Data-Engineering-Sec1/blob/main/Pandas_Day3_Titanic_Dataset_140_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

In [13]:
df=pd.read_csv("/content/Titanic-Dataset.csv")

In [16]:
df.shape

(891, 12)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         891 non-null    object
 1   Sex          891 non-null    object
 2   Age          714 non-null    float64
 3   SibSp        891 non-null    int64
 4   Parch        891 non-null    int64
 5   Embarked     889 non-null    object
 6   Ticket       891 non-null    object
 7   Fare         891 non-null    float64
 8   Cabin        204 non-null    object
 9   PassengerId  891 non-null    int64
 10  Pclass       891 non-null    int64
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [15]:
df.isnull().sum()

Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Embarked         2
Ticket           0
Fare             0
Cabin          687
PassengerId      0
Pclass           0
Survived         0
dtype: int64

In [17]:
df

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,0,S,A/5 21171,7.2500,NaN,1,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,0,S,STON/O2. 3101282,7.9250,NaN,3,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1
4,"Allen, Mr. William Henry",male,35.0,0,0,S,373450,8.0500,NaN,5,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,0,0,S,211536,13.0000,NaN,887,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,S,112053,30.0000,B42,888,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,S,W./C. 6607,23.4500,NaN,889,3,0
889,"Behr, Mr. Karl Howell",male,26.0,0,0,C,111369,30.0000,C148,890,1,1
890,"Dooley, Mr. Patrick",male,32.0,0,0,Q,370376,7.7500,NaN,891,3,0